spring:
  datasource:
    url: jdbc:mysql://localhost:3306/issues?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
server:
  max-http-header-size: 102400000